/**
 ****************************************************************************
 *
 * Copyright by Advantest Europe GmbH
 *
 ****************************************************************************
 */

#include "wifi/WifiOfdmCore.hpp"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>

namespace wifidemod {

namespace {

typedef std::complex<double> cd;

const double PI = 3.14159265358979323846;
const double TWO_PI = 2.0 * PI;
const int FFT_SIZE = 64;
const int DATA_CARRIERS = 48;
const int SIGNAL_SYMBOL = 2; // trellis index 0,1 = LTF1/LTF2, 2 = SIGNAL, 3+ = DATA

// IEEE 802.11-2016 17.3.3 Long Training Field, frequency domain content indexed by signed
// subcarrier k = -26..26 (sym[k + 26]); k=0 (DC) is unused/zero, as are |k| > 26 (guard band).
// Cross-verified against three independent sources: the gr-ieee802-11 project's
// utils/create_long.R generator script, its compiled lib/equalizer/base.cc::LONG[] constant
// (same values, offset by the 6 leading guard-band zeros), and the position<->subcarrier
// mapping implied by that project's pilot indices (11,25,39,53 -> k=-21,-7,7,21).
const int LTF_SYM[53] = {
     1,  1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,
     1,  0,
     1, -1, -1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1,  1
};

double ltfValue(int k)
{
  if (k < -26 || k > 26) return 0.0;
  return static_cast<double>(LTF_SYM[k + 26]);
}

bool isPilotSubcarrier(int k)
{
  return k == -21 || k == -7 || k == 7 || k == 21;
}

// Sign of the pilot subcarrier's reference value at k, excluding the per-symbol scrambling
// polarity p_n (17.3.5.9): {+1,+1,+1,-1} at k={-21,-7,7,21}.
double pilotBaseSign(int k)
{
  return k == 21 ? -1.0 : 1.0;
}

// 17.3.5.9: pilot polarity sequence p_n is the length-127 sequence generated by the scrambler
// (x^7+x^4+1, all-ones initial state), the same generator the DATA field scrambler uses.
// Generating it algorithmically (rather than transcribing a 127 entry magic-number table)
// removes any risk of a transcription error; verified bit-for-bit against the published
// reference sequence (gr-ieee802-11 utils/pilots.py) before being relied upon here.
std::vector<double> pilotPolaritySequence(int length)
{
  std::vector<double> out(length);
  unsigned state = 0x7Fu;
  for (int n = 0; n < length; ++n) {
    const unsigned feedback = ((state >> 3) ^ (state >> 6)) & 1u;
    out[n] = 1.0 - 2.0 * static_cast<double>(feedback);
    state = ((state << 1) | feedback) & 0x7Fu;
  }
  return out;
}

bool isDataSubcarrier(int k)
{
  return k != 0 && k >= -26 && k <= 26 && !isPilotSubcarrier(k);
}

// Radix-2 in-place FFT (self-contained: this core has no dependency on nr_core).
void fft64(std::vector<cd>& a, bool inverse)
{
  const size_t n = a.size();
  for (size_t i = 1, j = 0; i < n; ++i) {
    size_t bit = n >> 1;
    for (; j & bit; bit >>= 1) j ^= bit;
    j ^= bit;
    if (i < j) std::swap(a[i], a[j]);
  }
  for (size_t len = 2; len <= n; len <<= 1) {
    const double ang = TWO_PI / static_cast<double>(len) * (inverse ? 1.0 : -1.0);
    const cd wlen(std::cos(ang), std::sin(ang));
    for (size_t i = 0; i < n; i += len) {
      cd w(1.0, 0.0);
      for (size_t j = 0; j < len / 2; ++j) {
        const cd u = a[i + j];
        const cd v = a[i + j + len / 2] * w;
        a[i + j] = u + v;
        a[i + j + len / 2] = u - v;
        w *= wlen;
      }
    }
  }
}

int fftBin(int k)
{
  return ((k % FFT_SIZE) + FFT_SIZE) % FFT_SIZE;
}

// Time domain LTF waveform (64 samples), used as a matched filter: the LTF content is fully
// defined by the standard (unlike e.g. a data-modulated preamble), so direct correlation
// against the known waveform is both correct and simpler than blind self-correlation.
std::vector<cd> ltfTimeDomain()
{
  std::vector<cd> freq(FFT_SIZE, cd(0.0, 0.0));
  for (int k = -26; k <= 26; ++k) {
    const double v = ltfValue(k);
    if (v != 0.0) freq[fftBin(k)] = cd(v, 0.0);
  }
  fft64(freq, true);
  const double scale = 1.0 / std::sqrt(static_cast<double>(FFT_SIZE));
  for (auto& x : freq) x *= scale;
  return freq;
}

bool findBurst(const std::vector<cd>& iq, double thresholdDb, int& start, int& length)
{
  const int n = static_cast<int>(iq.size());
  if (n == 0) return false;
  const int window = std::max(8, n / 200);
  std::vector<double> powerDb(n);
  double sum = 0.0;
  for (int i = 0; i < n; ++i) {
    sum += std::norm(iq[i]);
    if (i >= window) sum -= std::norm(iq[i - window]);
    const int count = std::min(i + 1, window);
    const double mean = count > 0 ? sum / count : 0.0;
    powerDb[i] = 10.0 * std::log10(mean > 0.0 ? mean : 1e-30);
  }
  const double peakDb = *std::max_element(powerDb.begin(), powerDb.end());
  const double threshold = peakDb - std::fabs(thresholdDb);
  int first = -1, last = -1;
  for (int i = 0; i < n; ++i) {
    if (powerDb[i] >= threshold) {
      if (first < 0) first = i;
      last = i;
    }
  }
  if (first < 0) return false;
  start = first;
  length = last - first + 1;
  return length > 0;
}

double matchedFilterScore(const std::vector<cd>& iq, int pos, const std::vector<cd>& ltfTime)
{
  const int n = static_cast<int>(iq.size());
  if (pos < 0 || pos + FFT_SIZE > n) return 0.0;
  cd corr(0.0, 0.0);
  double energy = 0.0;
  for (int i = 0; i < FFT_SIZE; ++i) {
    corr += iq[pos + i] * std::conj(ltfTime[i]);
    energy += std::norm(iq[pos + i]);
  }
  const double denom = std::sqrt(energy * FFT_SIZE);
  return denom > 0.0 ? std::abs(corr) / denom : 0.0;
}

// Rate-1/2 K=7 convolutional code (IEEE 802.11-2016 17.3.5.5), state = last 7 encoded input
// bits packed LSB-first-newest; output parity taps 0155/0117 octal. Verified by direct
// transcription against the open-source gr-ieee802-11 utils.cc convolutional_encoding(), a
// widely used, independently tested reference implementation of this exact standard.
int parityOf(unsigned v)
{
  int p = 0;
  while (v) { p ^= (v & 1u); v >>= 1; }
  return p;
}

// Hard-decision Viterbi decode of a rate-1/2 K=7 convolutional code. 64 states (6 bit memory);
// a plain textbook implementation is used (rather than the SIMD/soft-decision production
// decoder) since only the 24 bit SIGNAL field needs decoding here - a tiny, latency
// insensitive amount of work where correctness and clarity matter far more than speed.
std::vector<int> viterbiDecodeRate1Half(const std::vector<int>& codedBits)
{
  const int numSteps = static_cast<int>(codedBits.size()) / 2;
  const int numStates = 64;
  const double INF = 1e18;
  std::vector<std::vector<double>> metric(numSteps + 1, std::vector<double>(numStates, INF));
  std::vector<std::vector<int>> prevState(numSteps + 1, std::vector<int>(numStates, -1));
  std::vector<std::vector<int>> prevBit(numSteps + 1, std::vector<int>(numStates, 0));
  metric[0][0] = 0.0;

  for (int step = 0; step < numSteps; ++step) {
    const int rx0 = codedBits[2 * step];
    const int rx1 = codedBits[2 * step + 1];
    for (int s = 0; s < numStates; ++s) {
      if (metric[step][s] >= INF) continue;
      for (int b = 0; b <= 1; ++b) {
        const unsigned v = static_cast<unsigned>((s << 1) | b) & 0x7Fu;
        const int out0 = parityOf(v & 0155u);
        const int out1 = parityOf(v & 0117u);
        const double cost = metric[step][s] + (out0 != rx0 ? 1.0 : 0.0) + (out1 != rx1 ? 1.0 : 0.0);
        const int next = static_cast<int>(v & 0x3Fu);
        if (cost < metric[step + 1][next]) {
          metric[step + 1][next] = cost;
          prevState[step + 1][next] = s;
          prevBit[step + 1][next] = b;
        }
      }
    }
  }

  int bestState = 0;
  double bestMetric = metric[numSteps][0];
  for (int s = 1; s < numStates; ++s) {
    if (metric[numSteps][s] < bestMetric) {
      bestMetric = metric[numSteps][s];
      bestState = s;
    }
  }

  std::vector<int> bits(numSteps);
  int state = bestState;
  for (int step = numSteps; step > 0; --step) {
    bits[step - 1] = prevBit[step][state];
    state = prevState[step][state];
  }
  return bits;
}

std::vector<int> deinterleaveSignalField(const std::vector<int>& received)
{
  const int nCbps = 48;
  std::vector<int> out(nCbps, 0);
  for (int k = 0; k < nCbps; ++k) {
    const int second = 16 * k - (nCbps - 1) * static_cast<int>(std::floor(16.0 * k / nCbps));
    out[second] = received[k];
  }
  return out;
}

cd hardDecisionBpsk(const cd& z)
{
  return cd(z.real() >= 0.0 ? 1.0 : -1.0, 0.0);
}

cd hardDecision(const cd& z, Modulation mod)
{
  switch (mod) {
    case MOD_BPSK: return hardDecisionBpsk(z);
    case MOD_QPSK: {
      const double s = 1.0 / std::sqrt(2.0);
      return cd(z.real() >= 0.0 ? s : -s, z.imag() >= 0.0 ? s : -s);
    }
    case MOD_QAM16: {
      const double s = 1.0 / std::sqrt(10.0);
      const auto axis = [&](double v) {
        double level = 2.0 * std::floor((v / s - 1.0) / 2.0 + 0.5) + 1.0;
        if (level > 3.0) level = 3.0;
        if (level < -3.0) level = -3.0;
        return level * s;
      };
      return cd(axis(z.real()), axis(z.imag()));
    }
    case MOD_QAM64:
    default: {
      const double s = 1.0 / std::sqrt(42.0);
      const auto axis = [&](double v) {
        double level = 2.0 * std::floor((v / s - 1.0) / 2.0 + 0.5) + 1.0;
        if (level > 7.0) level = 7.0;
        if (level < -7.0) level = -7.0;
        return level * s;
      };
      return cd(axis(z.real()), axis(z.imag()));
    }
  }
}

// 17.3.5.6 interleaver permutation indices for a general (n_bpsc, n_cbps) pairing, used for
// the DATA field (SIGNAL always uses the n_bpsc=1 special case handled separately above).
void dataInterleaverIndices(int nBpsc, int nCbps, std::vector<int>& first, std::vector<int>& second)
{
  const int s = std::max(nBpsc / 2, 1);
  first.assign(nCbps, 0);
  second.assign(nCbps, 0);
  for (int j = 0; j < nCbps; ++j) {
    first[j] = s * (j / s) + ((j + static_cast<int>(std::floor(16.0 * j / nCbps))) % s);
  }
  for (int i = 0; i < nCbps; ++i) {
    second[i] = 16 * i - (nCbps - 1) * static_cast<int>(std::floor(16.0 * i / nCbps));
  }
}

struct RateParams {
  Modulation modulation;
  int bpsc;
  int cbps;
  int dbps;
  int mbps;
};

bool rateFieldToParams(int rateField, RateParams& p)
{
  switch (rateField) {
    case 0x0D: p = {MOD_BPSK, 1, 48, 24, 6}; return true;
    case 0x0F: p = {MOD_BPSK, 1, 48, 36, 9}; return true;
    case 0x05: p = {MOD_QPSK, 2, 96, 48, 12}; return true;
    case 0x07: p = {MOD_QPSK, 2, 96, 72, 18}; return true;
    case 0x09: p = {MOD_QAM16, 4, 192, 96, 24}; return true;
    case 0x0B: p = {MOD_QAM16, 4, 192, 144, 36}; return true;
    case 0x01: p = {MOD_QAM64, 6, 288, 192, 48}; return true;
    case 0x03: p = {MOD_QAM64, 6, 288, 216, 54}; return true;
    default: return false;
  }
}

void codingRateForModulation(Modulation mod, int rateField, int& num, int& den)
{
  // the rate field distinguishes 1/2 vs 3/4 for BPSK/QPSK/16QAM (odd/even nibble pairing
  // above), and 2/3 vs 3/4 for 64QAM; read it back off the already-validated table instead
  // of re-deriving, to keep a single source of truth.
  (void)mod;
  switch (rateField) {
    case 0x0D: case 0x05: case 0x09: num = 1; den = 2; return;
    case 0x01: num = 2; den = 3; return;
    default: num = 3; den = 4; return;
  }
}

}

Config::Config() : sampleRate(0.0), burstSearch(true), burstSearchThresholdDb(15.0), syncThreshold(0.5)
{
}

Result::Result()
    : ok(false), burstFound(false), burstStart(0), burstLength(0), syncFound(false), syncRho(0.0),
      timingOffsetSamples(0), frequencyErrorHz(0.0), modulation(MOD_BPSK), codingRateNumerator(1),
      codingRateDenominator(2), dataRateMbps(0), psduLengthBytes(0), numDataSymbols(0), rmsEvmPercent(0.0),
      peakEvmPercent(0.0), peakEvmSymbolIndex(0), peakEvmSubcarrierIndex(0)
{
}

Result demodulate(const std::vector<cd>& iq, const Config& config)
{
  Result result;
  if (iq.empty() || config.sampleRate <= 0.0) {
    result.error = "empty capture or invalid sample rate";
    return result;
  }

  int burstStart = 0, burstLength = static_cast<int>(iq.size());
  if (config.burstSearch) {
    if (!findBurst(iq, config.burstSearchThresholdDb, burstStart, burstLength)) {
      result.error = "burst not found";
      return result;
    }
    result.burstFound = true;
  } else {
    result.burstFound = true;
  }
  result.burstStart = burstStart;
  result.burstLength = burstLength;

  // The receiver's own sample rate may differ from the 20 MHz the IEEE 802.11a preamble was
  // generated at; the FFT grid here is always 64 points at 20 MHz (312.5 kHz spacing), so
  // round the ratio to the nearest sample-for-sample mapping (TDC references are always
  // generated at exactly 20 MHz or an integer multiple thereof per the recorded ResampleRate).
  const double samplesPerFftSample = config.sampleRate / 20.0e6;
  if (samplesPerFftSample < 0.99 || std::fabs(samplesPerFftSample - std::llround(samplesPerFftSample)) > 1e-3) {
    result.error = "sample rate must be an integer multiple of 20 MHz";
    return result;
  }
  const int osr = static_cast<int>(std::llround(samplesPerFftSample));
  // decimate to exactly 20 MHz (osr=1 is the common, already-at-rate case)
  std::vector<cd> work;
  const std::vector<cd>* samples = &iq;
  if (osr != 1) {
    work.resize(iq.size() / osr);
    for (size_t i = 0; i < work.size(); ++i) work[i] = iq[i * osr];
    samples = &work;
    burstStart /= osr;
  }

  const std::vector<cd> ltfTime = ltfTimeDomain();
  const int searchEnd = std::min(static_cast<int>(samples->size()) - 2 * FFT_SIZE, burstStart + burstLength);
  double bestScore = -1.0;
  int bestPos = -1;
  for (int pos = burstStart; pos < searchEnd; ++pos) {
    const double score = matchedFilterScore(*samples, pos, ltfTime) + matchedFilterScore(*samples, pos + FFT_SIZE, ltfTime);
    if (score > bestScore) {
      bestScore = score;
      bestPos = pos;
    }
  }
  if (bestPos < 0) {
    result.error = "LTF not found in capture";
    return result;
  }
  result.timingOffsetSamples = (bestPos - burstStart) * osr;

  std::vector<cd> ltf1(samples->begin() + bestPos, samples->begin() + bestPos + FFT_SIZE);
  std::vector<cd> ltf2(samples->begin() + bestPos + FFT_SIZE, samples->begin() + bestPos + 2 * FFT_SIZE);
  fft64(ltf1, false);
  fft64(ltf2, false);
  const double fftScale = 1.0 / std::sqrt(static_cast<double>(FFT_SIZE));
  for (auto& v : ltf1) v *= fftScale;
  for (auto& v : ltf2) v *= fftScale;

  std::vector<cd> channel1(FFT_SIZE, cd(0.0, 0.0)), channel2(FFT_SIZE, cd(0.0, 0.0));
  for (int k = -26; k <= 26; ++k) {
    const double ref = ltfValue(k);
    if (ref == 0.0) continue;
    const int bin = fftBin(k);
    channel1[bin] = ltf1[bin] / ref;
    channel2[bin] = ltf2[bin] / ref;
  }

  cd crossSum(0.0, 0.0);
  double power1 = 0.0, power2 = 0.0;
  for (int k = -26; k <= 26; ++k) {
    if (ltfValue(k) == 0.0) continue;
    const int bin = fftBin(k);
    crossSum += channel2[bin] * std::conj(channel1[bin]);
    power1 += std::norm(channel1[bin]);
    power2 += std::norm(channel2[bin]);
  }
  const double denom = std::sqrt(power1 * power2);
  result.syncRho = denom > 0.0 ? std::abs(crossSum) / denom : 0.0;
  result.syncFound = result.syncRho >= config.syncThreshold;

  const double residualPhase = std::abs(crossSum) > 0.0 ? std::arg(crossSum) : 0.0;
  // channel2 = channel1 * exp(j * 2*pi*df*FFT_SIZE/Fs) when a carrier offset df accumulates
  // linearly across the one-FFT-period (64 sample) gap between the two LTF copies, so
  // residualPhase directly gives +df (no sign flip, unlike the UWB core's conjugate-order
  // convention) once solved for df.
  result.frequencyErrorHz = residualPhase * (20.0e6) / (TWO_PI * FFT_SIZE);

  std::vector<cd> channel(FFT_SIZE, cd(0.0, 0.0));
  const cd derotate = std::polar(1.0, -residualPhase);
  for (int bin = 0; bin < FFT_SIZE; ++bin) {
    channel[bin] = 0.5 * (channel1[bin] + channel2[bin] * derotate);
  }

  if (!result.syncFound) {
    result.ok = true; // burst/sync result still meaningful even when confidence is low
    return result;
  }

  // Residual carrier rotation per sample, applied symbol-by-symbol below so later OFDM
  // symbols (further from the LTF in time) are corrected too.
  const double residualRadPerSample = residualPhase / static_cast<double>(FFT_SIZE);

  // SIGNAL field: GI(16) + 64 samples, immediately after the two LTF copies.
  const int signalFftStart = bestPos + 2 * FFT_SIZE + 16;
  if (signalFftStart + FFT_SIZE > static_cast<int>(samples->size())) {
    result.error = "capture too short for the SIGNAL field";
    return result;
  }
  std::vector<cd> signalSym(samples->begin() + signalFftStart, samples->begin() + signalFftStart + FFT_SIZE);
  for (int i = 0; i < FFT_SIZE; ++i) {
    const double sampleIndex = static_cast<double>(signalFftStart + i - bestPos);
    signalSym[i] *= std::polar(1.0, -residualRadPerSample * sampleIndex);
  }
  fft64(signalSym, false);
  for (auto& v : signalSym) v *= fftScale;

  const std::vector<double> polarity = pilotPolaritySequence(127);
  // p_n index for SIGNAL (trellis symbol index 2) is (2-2)=0 per 17.3.5.9
  const double pSignal = polarity[0];
  cd signalPilotBeta(0.0, 0.0);
  for (const int k : {-21, -7, 7, 21}) {
    signalPilotBeta += signalSym[fftBin(k)] * std::conj(cd(pilotBaseSign(k) * pSignal, 0.0)) / channel[fftBin(k)];
  }
  const double signalBeta = std::abs(signalPilotBeta) > 0.0 ? std::arg(signalPilotBeta) : 0.0;
  const cd signalRotation = std::polar(1.0, -signalBeta);

  std::vector<int> signalBitsInterleaved(48);
  int signalBitPos = 0;
  for (int k = -26; k <= 26; ++k) {
    if (!isDataSubcarrier(k)) continue;
    const cd eq = signalSym[fftBin(k)] / channel[fftBin(k)] * signalRotation;
    signalBitsInterleaved[signalBitPos++] = eq.real() >= 0.0 ? 1 : 0;
  }
  const std::vector<int> signalDeinterleaved = deinterleaveSignalField(signalBitsInterleaved);
  const std::vector<int> signalDecodedBits = viterbiDecodeRate1Half(signalDeinterleaved);

  int rateField = 0;
  for (int b = 0; b < 4; ++b) rateField = (rateField << 1) | signalDecodedBits[b];
  RateParams rateParams;
  if (!rateFieldToParams(rateField, rateParams)) {
    result.error = "SIGNAL field decoded an invalid rate field";
    return result;
  }
  result.modulation = rateParams.modulation;
  result.dataRateMbps = rateParams.mbps;
  codingRateForModulation(rateParams.modulation, rateField, result.codingRateNumerator, result.codingRateDenominator);

  int lengthBytes = 0;
  for (int b = 0; b < 12; ++b) lengthBytes |= (signalDecodedBits[5 + b] << b);
  result.psduLengthBytes = lengthBytes;

  const int nSym = static_cast<int>(std::ceil((16.0 + 8.0 * lengthBytes + 6.0) / rateParams.dbps));
  result.numDataSymbols = nSym;
  if (nSym <= 0 || nSym > 10000) {
    result.error = "SIGNAL field decoded an implausible PSDU length";
    return result;
  }

  std::vector<int> firstPerm, secondPerm;
  dataInterleaverIndices(rateParams.bpsc, rateParams.cbps, firstPerm, secondPerm);

  double evmSumSquares = 0.0;
  double evmPeak = -1.0;
  long long evmCount = 0;
  int peakSymbol = 0, peakSubcarrier = 0;

  for (int sym = 0; sym < nSym; ++sym) {
    const int dataFftStart = bestPos + 2 * FFT_SIZE + 80 * (sym + 1) + 16;
    if (dataFftStart + FFT_SIZE > static_cast<int>(samples->size())) break;
    std::vector<cd> dataSym(samples->begin() + dataFftStart, samples->begin() + dataFftStart + FFT_SIZE);
    for (int i = 0; i < FFT_SIZE; ++i) {
      const double sampleIndex = static_cast<double>(dataFftStart + i - bestPos);
      dataSym[i] *= std::polar(1.0, -residualRadPerSample * sampleIndex);
    }
    fft64(dataSym, false);
    for (auto& v : dataSym) v *= fftScale;

    const double pData = polarity[(sym + 1) % 127]; // n = sym + 3 (first DATA symbol index=3) -> (n-2)%127 = (sym+1)%127
    cd pilotBeta(0.0, 0.0);
    for (const int k : {-21, -7, 7, 21}) {
      pilotBeta += dataSym[fftBin(k)] * std::conj(cd(pilotBaseSign(k) * pData, 0.0)) / channel[fftBin(k)];
    }
    const double beta = std::abs(pilotBeta) > 0.0 ? std::arg(pilotBeta) : 0.0;
    const cd rotation = std::polar(1.0, -beta);

    std::vector<cd> equalized(DATA_CARRIERS);
    int idx = 0;
    for (int k = -26; k <= 26; ++k) {
      if (!isDataSubcarrier(k)) continue;
      equalized[idx++] = dataSym[fftBin(k)] / channel[fftBin(k)] * rotation;
    }
    for (int c = 0; c < DATA_CARRIERS; ++c) {
      const cd decision = hardDecision(equalized[c], rateParams.modulation);
      const double err = std::norm(equalized[c] - decision);
      const double refPower = std::norm(decision) > 0.0 ? std::norm(decision) : 1.0;
      const double evmFraction = err / refPower;
      evmSumSquares += evmFraction;
      ++evmCount;
      if (evmFraction > evmPeak) {
        evmPeak = evmFraction;
        peakSymbol = sym;
        peakSubcarrier = c;
      }
    }
  }

  result.rmsEvmPercent = evmCount > 0 ? 100.0 * std::sqrt(evmSumSquares / static_cast<double>(evmCount)) : 0.0;
  result.peakEvmPercent = evmPeak >= 0.0 ? 100.0 * std::sqrt(evmPeak) : 0.0;
  result.peakEvmSymbolIndex = peakSymbol;
  result.peakEvmSubcarrierIndex = peakSubcarrier;

  result.ok = true;
  return result;
}

}
